"""Export coverage as a MITRE ATT&CK Navigator layer (importable at mitre-attack.github.io/attack-navigator)."""
from __future__ import annotations
from typing import Any, Dict, List
from .matrix import all_techniques
from .coverage import map_detections, Detection


def navigator_layer(detections: List[Detection], name: str = "Detection Coverage") -> Dict[str, Any]:
    """Build an ATT&CK Navigator (v4) layer scoring each technique by its
    detection count, so gaps (score 0) and hotspots stand out in the matrix view."""
    counts = map_detections(detections)
    techniques: List[Dict[str, Any]] = []
    for tid in all_techniques():
        c = counts.get(tid, 0)
        techniques.append({
            "techniqueID": tid,
            "score": c,
            "enabled": True,
            "comment": f"{c} detection(s)" if c else "no detection",
        })
    max_score = max(counts.values(), default=0)
    return {
        "name": name,
        "versions": {"layer": "4.5", "navigator": "4.9.1", "attack": "14"},
        "domain": "enterprise-attack",
        "description": "Generated by attackcov — score = number of detections per technique.",
        "techniques": techniques,
        "gradient": {
            "colors": ["#ff6666", "#ffe766", "#8ec843"],
            "minValue": 0,
            "maxValue": max(max_score, 1),
        },
        "legendItems": [],
    }
